# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210bb9b994b355b125a5bfd40e89a0e98d3130b0eea589e2cf2e8cca0130b7f1b891760088d0c0ec642246098948f9ee23777c4fe29925ee06217aef624125c4

test:
  secret_key_base: 2b5942e6af5a13ba8d92cbbca4124060fe09a5df3e52c124b03e7f5e82c177aa8ce328c553ad0624cc2c75ba90e36b2d2e85752ce137af4de03fa667ea0efc5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
